# Generated by Django 3.2.5 on 2021-07-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
