# Generated by Django 3.2.5 on 2021-07-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_samplepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SamplePost',
        ),
    ]
