# Generated by Django 3.2.5 on 2021-07-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_delete_samplepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.BooleanField(default=False),
        ),
    ]
